version: '3'

volumes:
  mdb-data:
  postgres-data:

networks:
  web:
    driver: bridge

services:
  pgsql:
    hostname: pgsql
    image: postgres
    restart: unless-stopped
    networks:
      - web
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  wechat-web:
    hostname: wechat-web
    image: wechat-web
    restart: unless-stopped
    build:
      context: ${LH_WECHAT_DIR}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - web
    depends_on:
      - pgsql
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:password@pgsql/lh_wechat
      - WECHAT_AUTH_BASE=https://open.weixin.qq.com/connect/oauth2/authorize
      - MDB_API_BASE=http://mdb-reader:3030
      - WECHAT_APP_ID=${WECHAT_APP_ID}
      - WECHAT_APP_SECRET=${WECHAT_APP_SECRET}
      - HOST_URL=${HOST_URL}
      - MD5_SALT=${MD5_SALT}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
  mdb-reader:
    hostname: mdb-reader
    image: mdb-reader
    restart: unless-stopped
    build:
      context: ${LH_MDB_DIR}
      dockerfile: Dockerfile
    networks:
      - web
    depends_on:
      - pgsql
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=postgres://postgres:password@pgsql/lh_mdb
    volumes:
      - mdb-data:/app/mdb
